default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: awdxqwikrmlnhi
  host: ec2-52-86-33-50.compute-1.amazonaws.com
  database: d39hatduloc1gr
  password: 899239b48185fb24ac6a917a22a9963d8bbaff0202a32c6a3c066834430ac68c